
spring:
  datasource: 
    class: org.springframework.jdbc.datasource.DriverManagerDataSourec
    driver-class-name: com.mysql.jdbc.Driver
    password: 1234
    url: "jdbc:mysql://localhost:3306/bookstore?createDatabaseIfNotExist=true"
    username: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
