spring:
  datasource:
    hikari:
        driver-class-name: com.mysql.jdbc.Driver
      
      jpa:
      hibernate:
          ddl-auto:true
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/bookstore
  jpa:
    hibernate:
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
