server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/madhushika-madhubhani/spring-cloud-config-store
          search-paths:
            -'*service'
         # repos: